# Generated by Django 4.2.3 on 2023-07-29 10:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("maestro", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="quiebre",
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name="quiebre",
            constraint=models.UniqueConstraint(
                fields=("institucion", "medicamento"), name="Llaves compuestas"
            ),
        ),
    ]
